### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by masterpowers** [Gert-dev/php-integrator-tooltips#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Microsoft Windows 8 Single Language
**Thrown From**: [php-integrator-tooltips](https://github.com/Gert-dev/php-integrator-tooltips) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /C:/Users/Uriah/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:30

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.buildTooltipForFunction (file:///C:/Users/Uriah/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:32:28)
    at MethodProvider.module.exports.MethodProvider.getTooltipForWord (file:///C:/Users/Uriah/.atom/packages/php-integrator-tooltips/lib/MethodProvider.coffee:27:24)
    at MethodProvider.module.exports.AbstractProvider.showPopoverFor (file:///C:/Users/Uriah/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:141:24)
    at HTMLSpanElement.<anonymous> (file:///C:/Users/Uriah/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:110:18)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\Uriah\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\Uriah\AppData\Local\atom\app-1.2.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -5:41.2.0 core:cancel (div.panels)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "creative-dark-syntax"
    ],
    "disabledPackages": [
      "atom-jshint",
      "jsformat",
      "atom-php-navigation",
      "css-snippets",
      "jquery-snippets",
      "jshint",
      "linter-csslint",
      "linter-htmlhint",
      "language-blade",
      "laravel",
      "php-cs-fixer",
      "linter-php",
      "linter",
      "aligner-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
color-picker, v2.0.13
creative-dark-syntax, v1.1.0
minimap, v4.16.1
php-integrator-annotations, v0.2.2
php-integrator-autocomplete-plus, v0.3.0
php-integrator-base, v0.3.0
php-integrator-navigation, v0.2.3
php-integrator-tooltips, v0.2.1

# Dev
No dev packages
```

**Comment by masterpowers** [comment]
this keeps showing when i press alt

**Comment by Gert-dev** [comment]
Do you still experience this issue? If so, do you have some code for me to look at? The parameters should never be be undefined for the value, so this may very well be a bug in the base package, which I sadly can't reproduce without a test case.

**Comment by kerwynrg** [comment]
@Gert-dev 
This issue is still happening

Atom: 1.4.1
Mac OS X: El capitan


Thrown:
Uncaught TypeError: Cannot read property 'length' of undefined
/Users/Developer/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37


TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.buildTooltipForFunction (/Users/Developer/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37:9)
    at ClassProvider.module.exports.ClassProvider.getTooltipForWord (/Users/Developer/.atom/packages/php-integrator-tooltips/lib/MethodProvider.coffee:27:24)
    at ClassProvider.module.exports.AbstractProvider.showPopoverFor (/Users/Developer/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:141:24)
    at HTMLSpanElement.<anonymous> (/Users/Developer/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:110:18)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by ricpelo** [comment]
I have the same problem, too.

**Comment by ricpelo** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [php-integrator-tooltips](https://github.com/Gert-dev/php-integrator-tooltips) package, v0.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/ricardo/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.buildTooltipForFunction (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/Utility.coffee:37:9)
    at FunctionDefinitionProvider.module.exports.FunctionDefinitionProvider.getTooltipForWord (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/FunctionDefinitionProvider.coffee:38:24)
    at FunctionDefinitionProvider.module.exports.AbstractProvider.showPopoverFor (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:139:24)
    at HTMLSpanElement.<anonymous> (/home/ricardo/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:108:18)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:26.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:26.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:26.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:16.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:move-left (atom-text-editor.editor.is-focused)
 16x -0:16.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.5.0 click (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "vim-mode"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yii2, v0.4.0
git-diff-details, v0.22.0
keyboard-localization, v1.4.14
language-latex, v0.6.1
linter, v1.11.3
linter-php, v1.1.8
linter-phpcs, v1.3.0
linter-tidy, v2.1.0
minimap, v4.19.0
php-cs-fixer, v2.5.6
php-extract-method, v0.2.1
php-integrator-annotations, v0.3.0
php-integrator-autocomplete-plus, v0.5.2
php-integrator-base, v0.6.2
php-integrator-call-tips, v0.2.1
php-integrator-navigation, v0.5.0
php-integrator-tooltips, v0.4.0
symbols-tree-view, v0.11.0
tabs-to-spaces, v1.0.2
vim-modeline, v0.4.0

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
Unfortunately I can't get Composer to run the command (it complains about the bower-asset/jquery dependency), I'm not really familiar enough with Yii to resolve this easily, is this a known problem? I've also tried your repository ricpelo/yii as it contains the same file and code on the line, does it occur for you there as well? When I reproduce it with this repository I get a `(No documentation available)` when I don't install the Composer dependencies and otherwise the documentation of the parent method (as expected).

I don't suspect this is the problem, but are you using PHP >= 5.4? The fact that it gets as far as `buildTooltipForFunction` seems to imply that the response from the PHP side was successfully retrieved andit actually contains data, but is somehow missing the `parameters` property. Could you perhaps put a debugger statement (or a breakpoint) at the location of the error and dump the contents of the `value` argument to see what's inside? Hopefully this will give me a clue to what is going wrong.

**Comment by ricpelo** [comment]
Oops! Sorry, @Gert-dev , it's my fault. Yii's documentation claims you need to type two `composer` commands, not one, as following:

```
composer global require "fxp/composer-asset-plugin:~1.1.1"
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
```

The `bower-asset/jquery` dependency problem is probably due to the missing first `composer` command.

My `ricpelo/yii` repository lacks of the `vendor/` directory, so using it isn't the same as using the aforementioned `composer` command. Please, tell me if your dependency problem aways using both two `composer` command.

Oh, and yes: I'm using PHP 5.5.9 ;).

Thank you very much for your time!

**Comment by Gert-dev** [comment]
Ok, thanks, I got it to download. Unfortunately, I still can't reproduce the issue; it just shows me nothing as long as it's indexing and then the correct tooltip when it's done indexing. No errors ever appear (not in the console either). Is there anything special about your setup you can think of, such as a symlinked path to your project folder? If you know how to work with the Chrome developer tools, you can always try `Ctrl+Shift+I`, go to `Sources`, press `Ctrl+P`, search for `Utility.coffee` (from the tootlips package) and put a breakpoint there. If you can consistently reproduce the error, you should get a `value` with no `parameters` data that's causing the error, I might be able to deduce something from the rest of the properties.

**Comment by ricpelo** [comment]
Thanks again for your reply. That's weird. I've purged all Atom stuff from my system (Ubuntu 14.04.4 64 bit):

```
sudo apt-get --purge remove atom
rm -rf ~/.atom
```

And do a fresh install using the `atom-amd64.deb` package downloaded from `atom.io`:

```
sudo dpkg -i atom-amd64.deb
```

And then I've used `apm` to install `php-integrator-base` and `php-integrator-tooltip`:

```
apm install php-integrator-base
apm install php-integrator-tooltip
```

With this clean setup, I absolutely still can reproduce the issue, with the same steps:

1. `composer global require "fxp/composer-asset-plugin:~1.1.1"`
2. `composer create-project --prefer-dist yiisoft/yii2-app-basic basic`
3. `cd basic`
4. `atom .`
5. Open `controllers/SiteController.php`
6. Move mouse cursor over `behaviors()` method name on line 14.

**Comment by ricpelo** [comment]
I've put a breakpoint inside `buildTooltipForFunction:` from `Utility.coffee`. Could this screenshot helps? It seems like `value` only contains `descriptions:` and `return:` fields.
![2016-02-21-212421_1280x1024_scrot](https://cloud.githubusercontent.com/assets/616169/13205173/ed14a57a-d8e1-11e5-9822-5bc2a847cbaf.png)

**Comment by ricpelo** [comment]
It worth noting that the issue can be reproduced hovering the mouse over `behavior()` and `actions()` methods from `SiteController.php` file, but all the other methods (starting with `action*()`) in that file works OK.

**Comment by ricpelo** [comment]
Interestingly, I've found a workaround: if I put a doc comment block just before the method definition (no matter its content), like this:

```
/**
 */
public function behaviors()
{
```

all works well.

![2016-02-21-225804_1280x1024_scrot](https://cloud.githubusercontent.com/assets/616169/13205733/0c8705b2-d8ef-11e5-9fb4-6c022dfdc6cb.png)

**Comment by ricpelo** [comment]
The problem is, obviously, in `php-integrator-base`, because also `php-integrator-symbol-viewer` is working bad with `SiteController.php` file, too. If `behaviors()` and `actions()` methods doesn't have a doc comment block, the `php-integrator-symbol-viewer` panel doesn't open. When I put a doc comment block in both of those methods, the panel shows all the symbols and everything works OK.

**Comment by Gert-dev** [comment]
I think I have good news: I seem to be able to reproduce it with PHP 5.5. The isue you are having is in fact the same as this one [1], so things are continuing happily on the PHP side while they are failing. I've released 0.6.6 of the base package which should fix it, could you confirm if it does for you as well?

[1] https://github.com/Gert-dev/php-integrator-base/issues/107

**Comment by ricpelo** [comment]
Yeah! I've just tested, and now it works perfectly! Thank you very much for your time and your great work :).

**Comment by Gert-dev** [comment]
No problem, thanks for sticking with me to debug this!
