### ISSUE TITLE
Documentation for children classes

### ISSUE THREAD

**Issue by riartem** [Gert-dev/php-integrator-tooltips#5]
Some architectures defines docs only in parent classes. And integrator-tooltips not seeing them.
Example:
I have class Request extends Kohana_Request.
Kohana_Request has docs. If it possible, make integrator-tooltips show parent's docs if children does not have own docs. Thank you.

(Sorry for my english, I am not native speaker)

**Comment by Gert-dev** [comment]
Thanks for reporting this. This is in fact an issue with the base package. I've created a new ticket for it there [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/56
